### ISSUE TITLE
Multiple resources from one author without a date

### ISSUE THREAD

**Issue by fargocram** [S4mHi6ru/CitationStyleFHNW#5]
If you have multiple resources from one author and this resources are dateless, Zotero doesn't add characters like a,b,c to identify the separate resources (e.g. Slamtec o.J. a, Slamtec o.J. b)

**Comment by JonathanSenn** [comment]
Same issue here - please fix

**Comment by S4mHi6ru** [comment]
same as here:
https://forums.zotero.org/discussion/17274/a-b-and-c-missing-for-no-date

**Comment by S4mHi6ru** [comment]
![photo_2017-10-12_12-33-53](https://user-images.githubusercontent.com/26566896/31492030-a05dbc72-af49-11e7-965d-950cc3f663ca.jpg)

is this better so?

**Comment by S4mHi6ru** [comment]
fixed in v1.4
